### PR TITLE
Issues #8 and #11 - web3 connect on Add Tip or Connect actions

### PR DESCRIPTION
**Pull request by maciejczypek**

### CODE REVIEW

**Comment by skuhlmann** [comment]
This looks good!

Couple of things to adjust:

1. Might be nice to detect if there is a cachedProvider and automatically connect if the user has previously connected in a different session.

Checkout https://github.com/tellor-io/tellorDisputeCenter/blob/master/src/contexts/Store.js

You just need to int the web3modal:
```
  const [web3Modal, setWeb3Modal] = useState(
    new Web3Modal({
      network: getChainData(+process.env.REACT_APP_CHAIN_ID).network, // optional
      providerOptions, // required
      cacheProvider: true,
    }),
  );
```

and then add the useEffect to initCurrent user if the cachedProvder is found.

**Comment by skuhlmann** [comment]
2. Can we now get rid of the src/utl/getWeb3.js file?

That would be nice - the infura key is hard coded in there.

**Comment by maciejczypek** [comment]
> 1. Can we now get rid of the src/utl/getWeb3.js file?
> 
> That would be nice - the infura key is hard coded in there.

Sure, if it's not used, I'll remove src/utl/getWeb3.js.
Also, I'll remove the key from the .env file, which I think shouldn't be even pushed, I created .env.example file for that reason, but also pushed this .env, because there were new properties so didn't want to push them empty.

**Comment by skuhlmann** [comment]
Awesome.

I don't think you put the key in there. It's legacy code:
https://github.com/tellor-io/tellorPriceView/blob/master/src/utils/getWeb3.js

**Comment by maciejczypek** [comment]
> This looks good!
> 
> Couple of things to adjust:
> 
> 1. Might be nice to detect if there is a cachedProvider and automatically connect if the user has previously connected in a different session.
> 
> Checkout https://github.com/tellor-io/tellorDisputeCenter/blob/master/src/contexts/Store.js
> 
> You just need to int the web3modal:
> 
> ```
>   const [web3Modal, setWeb3Modal] = useState(
>     new Web3Modal({
>       network: getChainData(+process.env.REACT_APP_CHAIN_ID).network, // optional
>       providerOptions, // required
>       cacheProvider: true,
>     }),
>   );
> ```
> 
> and then add the useEffect to initCurrent user if the cachedProvder is found.
> 
> also requires the w3connect function in auth,js seen here:
> https://github.com/tellor-io/tellorDisputeCenter/blob/master/src/utils/auth.js

Done. If provider has been cached, user will be automatically connected.

**Comment by maciejczypek** [comment]
Done too. I removed the file and also removed the Infura key from the .env file. Take a note, that after pulling changes, you'll have to fill the REACT_APP_INFURA_URI property in .env now.

**Comment by maciejczypek** [comment]
> 1. Can we now get rid of the src/utl/getWeb3.js file?
> 
> That would be nice - the infura key is hard coded in there.

Done too. I removed the file and also removed the Infura key from the .env file. Take a note, that after pulling changes, you'll have to fill the REACT_APP_INFURA_URI property in .env now.

**Comment by skuhlmann** [comment]
Looks great! nice work.

I'll merge + deploy + add this env variable to heroku @themandalore

**Pull request merged**
